=== edallade/Proyecto-WAD/Proecto WAD Struts-React/web/EjerciciosXchema.xsd
<?xml version="1.0"?>
<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="MissingWords">  
        <xs:complexType>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
                
                <xs:element name="test">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="testName" type="xs:string" minOccurs="0" maxOccurs="1"/>
                            <xs:element name="enunciado" type="xs:string" minOccurs="0" maxOccurs="1"/>
                            <xs:element name="missingWord" type="xs:string" minOccurs="0" maxOccurs="1"/>
                            <xs:element name="image" type="xs:string" minOccurs="0" maxOccurs="1"/>
                            <xs:element name="audio" type="xs:string" minOccurs="0" maxOccurs="1"/>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:integer" use="required"/>
                        <xs:attribute name="teacherID" type="xs:integer" use="optional"/>
                    </xs:complexType>
                </xs:element>
                
                <xs:element name="quiz">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="testID" type="xs:integer" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                        <xs:attribute name="teacherID" type="xs:integer" use="required"/>
                    </xs:complexType>
                </xs:element>
                                
            </xs:choice>
        </xs:complexType>
    </xs:element> 
</xs:schema>

=== edallade/Proyecto-WAD/Proecto WAD Struts-React/web/Ejercicios.xml
<?xml version="1.0" encoding="UTF-8"?>
<MissingWords xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="EjerciciosXchema.xsd">
    <test id="1" teacherID="2">
        <testName>Uno</testName>
        <enunciado>"Esto es un ", " para el ", " de WAD"</enunciado>
        <missingWord>"ejemplo", "ejercicio"</missingWord>
        <image>ejemplo.jpg</image>
        <audio>ejemplo.mp3</audio>
    </test>
    <test id="2" teacherID="2">
        <testName>Dos</testName>
        <enunciado>"", " esto es un ", " para el ", " de WAD"</enunciado>
        <missingWord>"Hola", "ejemplo", "ejercicio"</missingWord>
        <image>ejemplo.jpg</image>
        <audio>ejemplo.mp3</audio>
    </test>
    <test id="3" teacherID="2">
        <testName>Tres</testName>
        <enunciado>"Uno ", " Dos ", " Tres ", " Cuatro ", " Cinco ", ""</enunciado>
        <missingWord>"1", "2", "3", "4", "5"</missingWord>
        <image>ejemplo.jpg</image>
        <audio>ejemplo.mp3</audio>
    </test>
    <quiz quizID="1" teacherID="2">
        <name>Primer Examen</name>
        <testID>1</testID>
        <testID>2</testID>
        <testID>3</testID>
    </quiz>
</MissingWords>

=== edallade/Proyecto-WAD/Proecto WAD Struts-React/web/EjerciciosX.xml
<?xml version="1.0" encoding="UTF-8"?>
<MissingWords xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="EjerciciosXchema.xsd">
  <test id="1" teacherID="2">
    <testName>hI</testName>
    <enunciado>"Esto es un ", " para el ", " de WAD"</enunciado>
    <missingWord>"ejemplo", "ejercicio"</missingWord>
    <image>ejemplo.jpg</image>
    <audio>ejemplo.mp3</audio>
  </test>
  <test id="2" teacherID="2">
    <testName>Dos</testName>
    <enunciado>"", " esto es un ", " para el ", " de WAD"</enunciado>
    <missingWord>"Hola", "ejemplo", "ejercicio"</missingWord>
    <image>ejemplo.jpg</image>
    <audio>ejemplo.mp3</audio>
  </test>
  <test id="3" teacherID="2">
    <testName>Tres</testName>
    <enunciado>"", " esto es un ", " para el ", " de WAD"</enunciado>
    <missingWord>"Hola", "ejemplo", "ejercicio"</missingWord>
    <image>ejemplo.jpg</image>
    <audio>ejemplo.mp3</audio>
  </test>
  <test id="5" teacherID="2">
    <testName>Cuatro</testName>
    <enunciado>"", " esto es un ", " para el ", " de WAD"</enunciado>
    <missingWord>"Hola", "ejemplo", "ejercicio"</missingWord>
    <image>ejemplo.jpg</image>
    <audio>ejemplo.mp3</audio>
  </test>
  <quiz quizID="1" teacherID="2">
    <name>Primer Examen</name>
    <testID>1</testID>
    <testID>2</testID>
    <testID>3</testID>
  </quiz>
  <quiz quizID="1" teacherID="2">
    <name>Primer Examen</name>
    <testID>1</testID>
    <testID>2</testID>
    <testID>3</testID>
  </quiz>
  <quiz quizID="2" teacherID="2">
    <name>Prueba</name>
    <testID>1</testID>
  </quiz>
  <quiz quizID="3" teacherID="2">
    <name>Primer Examen</name>
    <testID>null</testID>
    <testID>null</testID>
  </quiz>
  <quiz quizID="4" teacherID="2">
    <name>a</name>
    <testID>null</testID>
  </quiz>
</MissingWords>
